### ISSUE TITLE
can't use vi_vn language

### ISSUE THREAD

**Issue by Keinamvy** [lenis0012/Translations#163]
When i change language to vi_vn in the config file it says the language is not exist

**Comment by MrSpeedy35** [comment]
Please check is the version is outdated.
Maybe the language was not added back then?
Please check now and if it does not work, respond here.

@lenis0012 Please close this issue if they do not respond within a week of this message.

**Comment by SaitDev** [comment]
@ImAhmadAbdullah @lenis0012 fixed in #214 
this issue has been here for like 4 years, from the start 😅
