### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by Rsanu** [lenis0012/Translations#76]
nie mogę zmienić loginsecurity na jezyk Polski

**Comment by lenis0012** [comment]
Please try to restart

**Comment by Rsanu** [comment]
nadal nie działa zmienam w configu pl_PL i nie działa

**Comment by lenis0012** [comment]
I just rebooted the translation server about 10 minutes ago. Are you certain it's not working?
You should set it to "pl_pl"

**Comment by Rsanu** [comment]
już wszystko działa dziękuje za pomoc :DD i przepraszam za trucie dupy XD
